name: build

on:
  schedule:
    - cron: 0 0 * * *

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: npm
    - name: Setup Git
      run: |-
        git config user.name "GitHub Actions"
        git config user.email "gpresland@gmail.com"
    - name: Generate File
      run: |-
        echo $(date) > $(date '+%Y-%m-%d').md
    - name: Publish
      run: |-
        git fetch origin gh-pages
        git switch gh-pages
        git add $(date '+%Y-%m-%d').md
        echo $(date) >> timestamps.log
        git add timestamps.log
        timestamp="$(date --utc)"
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push --force --set-upstream origin gh-pages
