name: build

on:
  push:
    branches:
      - main
  schedule:
    - cron:  "0 0 * * *"

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: npm
    - name: Setup git
      run: |-
        git config user.name "GitHub Actions"
        git config user.email "gpresland@gmail.com"
    # - name: Init app
    #   run: |-
    #     npm run init
    - name: Generate file
      run: |-
        echo $(date) > $(date '+%Y-%m-%d').md
    - name: Commit and push latest data
      run: |-
        git checkout -b gh-pages
        git add $(date '+%Y-%m-%d').md
        timestamp="$(date --utc)"
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
